version: '3.8' # Specify the Docker Compose file format version

services:
  frontend:
    build:
      context: . # Build context is the current directory (emptycup-app/)
      dockerfile: Dockerfile.frontend # Use the frontend Dockerfile
    ports:
      - "80:80" # Map host port 80 to container port 80
    depends_on:
      - backend # Ensure backend starts before frontend (for proxying)
    volumes:
      # Optional: Mount frontend files for live development if needed
      # - ./frontend:/usr/share/nginx/html
    networks:
      - emptycup_network # Assign to a custom network

  backend:
    build:
      context: . # Build context is the current directory (emptycup-app/)
      dockerfile: Dockerfile.backend # Use the backend Dockerfile
    ports:
      - "5000:5000" # Map host port 5000 to container port 5000 (though frontend proxies to it)
    volumes:
      # Optional: Mount backend files for live development (e.g., if you change app.py)
      # - ./backend:/app
    networks:
      - emptycup_network # Assign to the same custom network

networks:
  emptycup_network:
    driver: bridge # Define a custom bridge network for internal communication
